import React, { createContext, useContext, useState, useEffect } from 'react';

export type Language = 'nl' | 'en' | 'fr' | 'es' | 'it' | 'de';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  nl: {
    // Header
    'header.title': '🤖 Computerslet 3000',
    'header.support': 'Steun ons',
    'header.export': 'Exporteer',
    'header.import': 'Importeer',
    'header.logout': 'Uitloggen',
    'header.language': 'Taal',
    
    // Languages
    'language.nl': 'Nederlands',
    'language.en': 'Engels',
    'language.fr': 'Frans',
    'language.es': 'Spaans',
    'language.it': 'Italiaans',
    'language.de': 'Duits',
    
    // Auth
    'auth.title': 'Welkom bij Computerslet 3000',
    'auth.subtitle': 'Maak en beheer je informatietegels',
    'auth.login': 'Inloggen',
    'auth.signup': 'Registreren',
    'auth.email': 'E-mail',
    'auth.password': 'Wachtwoord',
    'auth.loginButton': 'Inloggen',
    'auth.signupButton': 'Account aanmaken',
    'auth.loginSuccess': 'Welkom terug!',
    'auth.loginSuccessDesc': 'Je bent succesvol ingelogd.',
    'auth.signupSuccess': 'Account aangemaakt!',
    'auth.signupSuccessDesc': 'Controleer je e-mail voor bevestiging.',
    'auth.loginError': 'Fout bij inloggen',
    'auth.signupError': 'Fout bij registreren',
    'auth.forgotPassword': 'Wachtwoord vergeten?',
    'auth.resetPassword': 'Wachtwoord resetten',
    'auth.resetPasswordButton': 'Reset instructies verzenden',
    'auth.resetPasswordSuccess': 'Reset instructies verzonden',
    'auth.resetPasswordSuccessDesc': 'Controleer je e-mail voor reset instructies',
    'auth.resetPasswordError': 'Fout bij resetten wachtwoord',
    'auth.backToLogin': 'Terug naar inloggen',
    'auth.newPassword': 'Nieuw wachtwoord',
    'auth.confirmPassword': 'Bevestig wachtwoord',
    'auth.updatePassword': 'Wachtwoord bijwerken',
    'auth.updatePasswordButton': 'Wachtwoord bijwerken',
    'auth.passwordsDoNotMatch': 'Wachtwoorden komen niet overeen',
    'auth.passwordUpdated': 'Wachtwoord bijgewerkt',
    'auth.passwordUpdatedDesc': 'Je wachtwoord is succesvol bijgewerkt',
    'auth.passwordUpdateError': 'Fout bij bijwerken wachtwoord',
    
    // Auth errors
    'auth.error.invalidCredentials': 'Onjuiste inloggegevens',
    'auth.error.userExists': 'Gebruiker al geregistreerd',
    'auth.error.emailNotConfirmed': 'E-mail niet bevestigd',
    'auth.error.passwordTooShort': 'Wachtwoord moet minimaal 6 tekens lang zijn',
    'auth.error.invalidEmail': 'Ongeldig e-mailadres',
    'auth.error.rateLimited': 'Te veel verzoeken. Probeer het later opnieuw',
    'auth.error.linkExpired': 'Link is ongeldig of verlopen',
    'auth.error.samePassword': 'Nieuw wachtwoord moet anders zijn dan het oude',
    
    // Dashboard
    'dashboard.loading': 'Laden...',
    'dashboard.addTile': 'Nieuwe tegel toevoegen',
    'dashboard.editTile': 'Tegel bewerken',
    'dashboard.exampleTitle': 'Voorbeeld',
    'dashboard.exampleContent': 'Hey, je hebt zojuist je eerste tegel gekopieerd! Je kunt meer tegels toevoegen met aangepaste tekst en afbeeldingen om je repeterende werk/antwoorden/berichten veel gemakkelijker te kopiëren en plakken.',
    'dashboard.instruction': 'Klik op een tegel om de tekst te kopiëren. Gebruik ✏️ om te bewerken of 🗑️ om te verwijderen.',
    
    // Tile form
    'tile.title': 'Titel',
    'tile.content': 'Inhoud',
    'tile.color': 'Kleur',
    'tile.save': 'Opslaan',
    'tile.cancel': 'Annuleren',
    'tile.delete': 'Verwijderen',
    'tile.created': 'Tegel aangemaakt',
    'tile.updated': 'Tegel bijgewerkt',
    'tile.deleted': 'Tegel verwijderd',
    'tile.subject': 'Onderwerp:',
    'tile.text': 'Tekst:',
    'tile.editTitle': '✏️ Tegel bewerken',
    'tile.addTitle': '➕ Nieuwe tegel toevoegen',
    'tile.saveButton': '💾 Bewaar',
    'tile.saving': 'Bezig...',
    'tile.copySms': 'SMS-veilige versie kopiëren',
    'tile.edit': 'Bewerken',
    'tile.deleteTooltip': 'Verwijderen',
    'tile.confirmDelete': 'Weet je zeker dat je deze tegel wilt verwijderen?',
    'tile.copied': '✓ Tekst gekopieerd',
    'tile.copiedMultiFormat': 'Meerdere formaten: HTML, Markdown, RTF, plain text',
    'tile.copiedHtmlPlain': 'HTML en plain text gekopieerd',
    'tile.copiedPlain': 'Plain text gekopieerd',
    'tile.smsModified': '⚠️ Let op: de tekst werd aangepast',
    'tile.smsCopied': '✓ De tegel is gekopieerd',
    'tile.copyFailed': 'Kopiëren mislukt',
    'tile.copyFailedDesc': 'Kon SMS-versie niet naar klembord kopiëren',
    'tile.characters': 'tekens',
    
    share: {
      button: 'Deel',
      createLink: 'Deelbare link',
      selectTiles: 'Selecteer tegels om te delen',
      selectTilesDesc: 'Kies welke tegels je wilt delen met anderen',
      selectDashboard: 'Kies dashboard',
      selectDashboardDesc: 'Selecteer welk dashboard je wilt delen',
      collectionName: 'Verzameling naam',
      collectionNamePlaceholder: 'Mijn gedeelde tegels',
      selectAll: 'Alles selecteren',
      deselectAll: 'Alles deselecteren',
      selected: 'geselecteerd',
      cancel: 'Annuleren',
      creating: 'Maken...',
      success: 'Deelbare link gemaakt',
      successDesc: 'Je kunt nu deze link delen met anderen',
      error: 'Fout bij maken link',
      linkCreated: 'Deelbare link gemaakt!',
      linkCreatedDesc: 'Kopieer de onderstaande link om je tegels te delen',
      shareUrl: 'Deel URL',
      copy: 'Kopiëren',
      copied: 'Gekopieerd!',
      copiedDesc: 'De link is gekopieerd naar je klembord',
      copyError: 'Kopiëren mislukt',
      copyErrorDesc: 'Kon de link niet kopiëren',
      close: 'Sluiten',
      defaultName: 'Gedeelde tegels',
      loading: 'Laden...',
      notFound: 'Gedeelde verzameling niet gevonden',
      notFoundDesc: 'Deze link is ongeldig of verlopen.',
      collectionDesc: 'Gedeelde tegelverzameling',
      noTiles: 'Geen tegels in deze verzameling',
    },
    dashboard: {
      select: 'Selecteer tegelverzameling',
      new: 'Nieuwe tegelverzameling',
      newTitle: 'Nieuwe tegelverzameling maken',
      newDesc: 'Geef je nieuwe tegelverzameling een naam',
      name: 'Tegelverzameling naam',
      namePlaceholder: 'Mijn tegelverzameling',
      cancel: 'Annuleren',
      create: 'Maken',
      creating: 'Maken...',
      created: 'Tegelverzameling gemaakt',
      createdDesc: 'Je nieuwe tegelverzameling is klaar',
      createError: 'Fout bij maken tegelverzameling',
      delete: 'Verwijderen',
      deleted: 'Tegelverzameling verwijderd',
      deletedDesc: 'De tegelverzameling is verwijderd',
      deleteError: 'Fout bij verwijderen tegelverzameling',
      cannotDelete: 'Kan niet verwijderen',
      cannotDeleteDesc: 'Je moet minstens één tegelverzameling hebben',
      rename: 'Hernoemen',
      renameTitle: 'Tegelverzameling hernoemen',
      renameDesc: 'Geef je tegelverzameling een nieuwe naam',
      renamed: 'Tegelverzameling hernoemd',
      renamedDesc: 'Je tegelverzameling naam is bijgewerkt',
      renameError: 'Fout bij hernoemen tegelverzameling',
    },
    'donation.title': 'Steun Computerslet 3000',
    'donation.description': 'Maakt de Computerslet 3000 jou ook zo gelukkig? Overweeg dan om je Computerpimp een fooi te geven. Zo kan hij ervoor zorgen dat je Computerslet 3000 haar werk zal blijven doen.',
    'donation.amount': 'Donatiebedrag',
    'donation.custom': 'Aangepast bedrag',
    'donation.donate': 'Doneren',
    'donation.processing': 'Bezig met verwerken...',
    'donation.copied': 'Gekopieerd!',
    'donation.copySuccess': 'Rekeningnummer is gekopieerd naar klembord',
    'donation.copyError': 'Kon rekeningnummer niet kopiëren',
    'donation.bankTransfer': 'Bankovermaking (gratis)',
    'donation.bankDesc': 'Maak een overmaking naar onze Belgische KBC-rekening',
    'donation.accountNumber': 'Rekeningnummer:',
    'donation.reference': 'Vermeld bij de mededeling: "Donatie Computerslet 3000"',
    'donation.onlinePayment': 'Online betaling (Stripe)',
    'donation.onlineDesc': 'Betaal veilig met creditcard, bancontact of andere betaalmethoden',
    'donation.invalidAmount': 'Ongeldig bedrag',
    'donation.minAmount': 'Voer een geldig bedrag in (minimaal €1)',
    'donation.stripeNotice': '* Online betalingen worden verwerkt door Stripe. Er kunnen transactiekosten van toepassing zijn.',
    'donation.thankYou': 'Dank je wel voor je steun! ❤️',
    'donation.helpText': 'Jouw bijdrage helpt ons om Computerslet 3000 nog beter te maken.',
    'donation.processError': 'Er is een fout opgetreden bij het verwerken van de donatie',
    
    // Donation success
    'donationSuccess.title': 'Bedankt voor je donatie!',
    'donationSuccess.description': 'Je betaling is succesvol verwerkt. We waarderen je steun enorm!',
    'donationSuccess.helpText': 'Je bijdrage helpt ons om Computerslet 3000 te blijven ontwikkelen en verbeteren.',
    'donationSuccess.backButton': 'Terug naar Computerslet 3000',
    'donationSuccess.autoRedirect': 'Je wordt automatisch doorgestuurd over 10 seconden...',
    
    // Common
    'common.home': 'Home',
    'common.error': 'Er is een fout opgetreden',
    'common.success': 'Succesvol',
    
    // Export/Import
    'export.success': '📤 Export voltooid',
    'export.successDesc': 'tegels geëxporteerd.',
    'export.selectTiles': 'Selecteer tegels om te exporteren',
    'export.selectTilesDesc': 'Kies welke tegels je wilt exporteren.',
    'import.success': '📥 Import voltooid',
    'import.successDesc': 'tegels geïmporteerd.',
    'import.error': 'Fout bij importeren',
    'import.errorDesc': 'Het bestand kon niet worden gelezen. Controleer het formaat.',
    
    // Logout
    'logout.success': 'Tot ziens!',
    'logout.successDesc': 'Je bent succesvol uitgelogd.',
    'logout.error': 'Fout bij uitloggen',
    
    // 404
    'notFound.title': '404',
    'notFound.description': 'Oops! Pagina niet gevonden',
    'notFound.backLink': 'Terug naar Home',
  },
  en: {
    // Header
    'header.title': '🤖 Computerslet 3000',
    'header.support': 'Support us',
    'header.export': 'Export',
    'header.import': 'Import',
    'header.logout': 'Logout',
    'header.language': 'Language',
    
    // Languages
    'language.nl': 'Dutch',
    'language.en': 'English',
    'language.fr': 'French',
    'language.es': 'Spanish',
    'language.it': 'Italian',
    'language.de': 'German',
    
    // Auth
    'auth.title': 'Welcome to Computerslet 3000',
    'auth.subtitle': 'Create and manage your information tiles',
    'auth.login': 'Login',
    'auth.signup': 'Sign up',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.loginButton': 'Login',
    'auth.signupButton': 'Create account',
    'auth.loginSuccess': 'Welcome back!',
    'auth.loginSuccessDesc': 'You have been successfully logged in.',
    'auth.signupSuccess': 'Account created!',
    'auth.signupSuccessDesc': 'Check your email for confirmation.',
    'auth.loginError': 'Login error',
    'auth.signupError': 'Registration error',
    'auth.forgotPassword': 'Forgot password?',
    'auth.resetPassword': 'Reset password',
    'auth.resetPasswordButton': 'Send reset instructions',
    'auth.resetPasswordSuccess': 'Reset instructions sent',
    'auth.resetPasswordSuccessDesc': 'Check your email for reset instructions',
    'auth.resetPasswordError': 'Password reset error',
    'auth.backToLogin': 'Back to login',
    'auth.newPassword': 'New password',
    'auth.confirmPassword': 'Confirm password',
    'auth.updatePassword': 'Update password',
    'auth.updatePasswordButton': 'Update password',
    'auth.passwordsDoNotMatch': 'Passwords do not match',
    'auth.passwordUpdated': 'Password updated',
    'auth.passwordUpdatedDesc': 'Your password has been successfully updated',
    'auth.passwordUpdateError': 'Password update error',
    
    // Auth errors
    'auth.error.invalidCredentials': 'Invalid login credentials',
    'auth.error.userExists': 'User already registered',
    'auth.error.emailNotConfirmed': 'Email not confirmed',
    'auth.error.passwordTooShort': 'Password must be at least 6 characters',
    'auth.error.invalidEmail': 'Invalid email address',
    'auth.error.rateLimited': 'Too many requests. Please try again later',
    'auth.error.linkExpired': 'Link is invalid or has expired',
    'auth.error.samePassword': 'New password must be different from the old one',
    
    // Dashboard
    'dashboard.loading': 'Loading...',
    'dashboard.addTile': 'Add new tile',
    'dashboard.editTile': 'Edit tile',
    'dashboard.exampleTitle': 'Example',
    'dashboard.exampleContent': 'Hey, you just copied your first tile! You can add more tiles with custom text and images to make your repeating work/answers/messages way more easy to copy-paste.',
    'dashboard.instruction': 'Click on a tile to copy the text. Use ✏️ to edit or 🗑️ to delete.',
    
    // Tile form
    'tile.title': 'Title',
    'tile.content': 'Content',
    'tile.color': 'Color',
    'tile.save': 'Save',
    'tile.cancel': 'Cancel',
    'tile.delete': 'Delete',
    'tile.created': 'Tile created',
    'tile.updated': 'Tile updated',
    'tile.deleted': 'Tile deleted',
    'tile.subject': 'Subject:',
    'tile.text': 'Text:',
    'tile.editTitle': '✏️ Edit tile',
    'tile.addTitle': '➕ Add new tile',
    'tile.saveButton': '💾 Save',
    'tile.saving': 'Saving...',
    'tile.copySms': 'Copy SMS-safe version',
    'tile.edit': 'Edit',
    'tile.deleteTooltip': 'Delete',
    'tile.confirmDelete': 'Are you sure you want to delete this tile?',
    'tile.copied': '✓ Text copied',
    'tile.copiedMultiFormat': 'Multiple formats: HTML, Markdown, RTF, plain text',
    'tile.copiedHtmlPlain': 'HTML and plain text copied',
    'tile.copiedPlain': 'Plain text copied',
    'tile.smsModified': '⚠️ Warning: text was modified',
    'tile.smsCopied': '✓ Tile copied',
    'tile.copyFailed': 'Copy failed',
    'tile.copyFailedDesc': 'Could not copy SMS version to clipboard',
    'tile.characters': 'characters',
    
    share: {
      button: 'Share',
      createLink: 'Shareable link',
      selectTiles: 'Select tiles to share',
      selectTilesDesc: 'Choose which tiles you want to share with others',
      selectDashboard: 'Choose dashboard',
      selectDashboardDesc: 'Select which dashboard you want to share',
      collectionName: 'Collection name',
      collectionNamePlaceholder: 'My shared tiles',
      selectAll: 'Select all',
      deselectAll: 'Deselect all',
      selected: 'selected',
      cancel: 'Cancel',
      creating: 'Creating...',
      success: 'Shareable link created',
      successDesc: 'You can now share this link with others',
      error: 'Error creating link',
      linkCreated: 'Shareable link created!',
      linkCreatedDesc: 'Copy the link below to share your tiles',
      shareUrl: 'Share URL',
      copy: 'Copy',
      copied: 'Copied!',
      copiedDesc: 'The link has been copied to your clipboard',
      copyError: 'Copy failed',
      copyErrorDesc: 'Could not copy the link',
      close: 'Close',
      defaultName: 'Shared tiles',
      loading: 'Loading...',
      notFound: 'Shared collection not found',
      notFoundDesc: 'This link is invalid or has expired.',
      collectionDesc: 'Shared tile collection',
      noTiles: 'No tiles in this collection',
    },
    dashboard: {
      select: 'Select tile collection',
      new: 'New tile collection',
      newTitle: 'Create new tile collection',
      newDesc: 'Give your new tile collection a name',
      name: 'Tile collection name',
      namePlaceholder: 'My tile collection',
      cancel: 'Cancel',
      create: 'Create',
      creating: 'Creating...',
      created: 'Tile collection created',
      createdDesc: 'Your new tile collection is ready',
      createError: 'Error creating tile collection',
      delete: 'Delete',
      deleted: 'Tile collection deleted',
      deletedDesc: 'The tile collection has been deleted',
      deleteError: 'Error deleting tile collection',
      cannotDelete: 'Cannot delete',
      cannotDeleteDesc: 'You must have at least one tile collection',
      rename: 'Rename',
      renameTitle: 'Rename tile collection',
      renameDesc: 'Give your tile collection a new name',
      renamed: 'Tile collection renamed',
      renamedDesc: 'Your tile collection name has been updated',
      renameError: 'Error renaming tile collection',
    },
    'donation.title': 'Support Computerslet 3000',
    'donation.description': 'Does Computerslet 3000 make you happy too? Consider giving your Computer pimp a tip. This way he can ensure that your Computerslet 3000 will continue to do her work.',
    'donation.amount': 'Donation amount',
    'donation.custom': 'Custom amount',
    'donation.donate': 'Donate',
    'donation.processing': 'Processing...',
    'donation.copied': 'Copied!',
    'donation.copySuccess': 'Account number copied to clipboard',
    'donation.copyError': 'Could not copy account number',
    'donation.bankTransfer': 'Bank transfer (free)',
    'donation.bankDesc': 'Transfer to our Belgian KBC account',
    'donation.accountNumber': 'Account number:',
    'donation.reference': 'Mention in communication: "Donation Computerslet 3000"',
    'donation.onlinePayment': 'Online payment (Stripe)',
    'donation.onlineDesc': 'Pay safely with credit card, bancontact or other payment methods',
    'donation.invalidAmount': 'Invalid amount',
    'donation.minAmount': 'Enter a valid amount (minimum €1)',
    'donation.stripeNotice': '* Online payments are processed by Stripe. Transaction fees may apply.',
    'donation.thankYou': 'Thank you for your support! ❤️',
    'donation.helpText': 'Your contribution helps us make Computerslet 3000 even better.',
    'donation.processError': 'An error occurred while processing the donation',
    
    // Donation success
    'donationSuccess.title': 'Thank you for your donation!',
    'donationSuccess.description': 'Your payment has been successfully processed. We greatly appreciate your support!',
    'donationSuccess.helpText': 'Your contribution helps us continue to develop and improve Computerslet 3000.',
    'donationSuccess.backButton': 'Back to Computerslet 3000',
    'donationSuccess.autoRedirect': 'You will be automatically redirected in 10 seconds...',
    
    // Common
    'common.home': 'Home',
    'common.error': 'An error occurred',
    'common.success': 'Success',
    
    // Export/Import
    'export.success': '📤 Export completed',
    'export.successDesc': 'tiles exported.',
    'export.selectTiles': 'Select tiles to export',
    'export.selectTilesDesc': 'Choose which tiles you want to export.',
    'import.success': '📥 Import completed',
    'import.successDesc': 'tiles imported.',
    'import.error': 'Import error',
    'import.errorDesc': 'The file could not be read. Check the format.',
    
    // Logout
    'logout.success': 'Goodbye!',
    'logout.successDesc': 'You have been successfully logged out.',
    'logout.error': 'Logout error',
    
    // 404
    'notFound.title': '404',
    'notFound.description': 'Oops! Page not found',
    'notFound.backLink': 'Return to Home',
  },
  fr: {
    // Header
    'header.title': '🤖 Computerslet 3000',
    'header.support': 'Soutenez-nous',
    'header.export': 'Exporter',
    'header.import': 'Importer',
    'header.logout': 'Déconnexion',
    'header.language': 'Langue',
    
    // Languages
    'language.nl': 'Néerlandais',
    'language.en': 'Anglais',
    'language.fr': 'Français',
    'language.es': 'Espagnol',
    'language.it': 'Italien',
    'language.de': 'Allemand',
    
    // Auth
    'auth.title': 'Bienvenue sur Computerslet 3000',
    'auth.subtitle': 'Créez et gérez vos tuiles d\'information',
    'auth.login': 'Connexion',
    'auth.signup': 'Inscription',
    'auth.email': 'E-mail',
    'auth.password': 'Mot de passe',
    'auth.loginButton': 'Se connecter',
    'auth.signupButton': 'Créer un compte',
    'auth.loginSuccess': 'Bon retour !',
    'auth.loginSuccessDesc': 'Vous êtes connecté avec succès.',
    'auth.signupSuccess': 'Compte créé !',
    'auth.signupSuccessDesc': 'Vérifiez votre e-mail pour confirmation.',
    'auth.loginError': 'Erreur de connexion',
    'auth.signupError': 'Erreur d\'inscription',
    'auth.forgotPassword': 'Mot de passe oublié?',
    'auth.resetPassword': 'Réinitialiser le mot de passe',
    'auth.resetPasswordButton': 'Envoyer les instructions',
    'auth.resetPasswordSuccess': 'Instructions envoyées',
    'auth.resetPasswordSuccessDesc': 'Vérifiez votre e-mail pour les instructions',
    'auth.resetPasswordError': 'Erreur de réinitialisation',
    'auth.backToLogin': 'Retour à la connexion',
    'auth.newPassword': 'Nouveau mot de passe',
    'auth.confirmPassword': 'Confirmer le mot de passe',
    'auth.updatePassword': 'Mettre à jour le mot de passe',
    'auth.updatePasswordButton': 'Mettre à jour le mot de passe',
    'auth.passwordsDoNotMatch': 'Les mots de passe ne correspondent pas',
    'auth.passwordUpdated': 'Mot de passe mis à jour',
    'auth.passwordUpdatedDesc': 'Votre mot de passe a été mis à jour avec succès',
    'auth.passwordUpdateError': 'Erreur de mise à jour du mot de passe',
    
    // Auth errors
    'auth.error.invalidCredentials': 'Identifiants de connexion invalides',
    'auth.error.userExists': 'Utilisateur déjà enregistré',
    'auth.error.emailNotConfirmed': 'E-mail non confirmé',
    'auth.error.passwordTooShort': 'Le mot de passe doit contenir au moins 6 caractères',
    'auth.error.invalidEmail': 'Adresse e-mail invalide',
    'auth.error.rateLimited': 'Trop de requêtes. Veuillez réessayer plus tard',
    'auth.error.linkExpired': 'Le lien est invalide ou a expiré',
    'auth.error.samePassword': 'Le nouveau mot de passe doit être différent de l\'ancien',
    
    // Dashboard
    'dashboard.loading': 'Chargement...',
    'dashboard.addTile': 'Ajouter une nouvelle tuile',
    'dashboard.editTile': 'Modifier la tuile',
    'dashboard.exampleTitle': 'Exemple',
    'dashboard.exampleContent': 'Hé, vous venez de copier votre première tuile ! Vous pouvez ajouter plus de tuiles avec du texte et des images personnalisés pour faciliter la copie-coller de vos travaux/réponses/messages répétitifs.',
    'dashboard.instruction': 'Cliquez sur une tuile pour copier le texte. Utilisez ✏️ pour modifier ou 🗑️ pour supprimer.',
    
    // Tile form
    'tile.title': 'Titre',
    'tile.content': 'Contenu',
    'tile.color': 'Couleur',
    'tile.save': 'Enregistrer',
    'tile.cancel': 'Annuler',
    'tile.delete': 'Supprimer',
    'tile.created': 'Tuile créée',
    'tile.updated': 'Tuile mise à jour',
    'tile.deleted': 'Tuile supprimée',
    'tile.subject': 'Sujet:',
    'tile.text': 'Texte:',
    'tile.editTitle': '✏️ Modifier la tuile',
    'tile.addTitle': '➕ Ajouter une nouvelle tuile',
    'tile.saveButton': '💾 Enregistrer',
    'tile.saving': 'Enregistrement...',
    'tile.copySms': 'Copier version SMS-safe',
    'tile.edit': 'Modifier',
    'tile.deleteTooltip': 'Supprimer',
    'tile.confirmDelete': 'Êtes-vous sûr de vouloir supprimer cette tuile?',
    'tile.copied': '✓ Texte copié',
    'tile.copiedMultiFormat': 'Plusieurs formats: HTML, Markdown, RTF, texte brut',
    'tile.copiedHtmlPlain': 'HTML et texte brut copiés',
    'tile.copiedPlain': 'Texte brut copié',
    'tile.smsModified': '⚠️ Attention: le texte a été modifié',
    'tile.smsCopied': '✓ Tuile copiée',
    'tile.copyFailed': 'Échec de la copie',
    'tile.copyFailedDesc': 'Impossible de copier la version SMS dans le presse-papiers',
    'tile.characters': 'caractères',
    
    share: {
      button: 'Partager',
      createLink: 'Lien partageable',
      selectTiles: 'Sélectionner les tuiles à partager',
      selectTilesDesc: 'Choisissez les tuiles que vous voulez partager avec d\'autres',
      selectDashboard: 'Choisir tableau de bord',
      selectDashboardDesc: 'Sélectionnez quel tableau de bord vous voulez partager',
      collectionName: 'Nom de la collection',
      collectionNamePlaceholder: 'Mes tuiles partagées',
      selectAll: 'Tout sélectionner',
      deselectAll: 'Tout désélectionner',
      selected: 'sélectionné',
      cancel: 'Annuler',
      creating: 'Création...',
      success: 'Lien partageable créé',
      successDesc: 'Vous pouvez maintenant partager ce lien avec d\'autres',
      error: 'Erreur lors de la création du lien',
      linkCreated: 'Lien partageable créé !',
      linkCreatedDesc: 'Copiez le lien ci-dessous pour partager vos tuiles',
      shareUrl: 'URL de partage',
      copy: 'Copier',
      copied: 'Copié !',
      copiedDesc: 'Le lien a été copié dans votre presse-papiers',
      copyError: 'Échec de la copie',
      copyErrorDesc: 'Impossible de copier le lien',
      close: 'Fermer',
      defaultName: 'Tuiles partagées',
      loading: 'Chargement...',
      notFound: 'Collection partagée non trouvée',
      notFoundDesc: 'Ce lien est invalide ou a expiré.',
      collectionDesc: 'Collection de tuiles partagées',
      noTiles: 'Aucune tuile dans cette collection',
    },

    export: {
      selectTiles: 'Sélectionner les tuiles à exporter',
      selectTilesDesc: 'Choisissez les tuiles que vous voulez exporter',
      selectDashboard: 'Choisir tableau de bord',
      selectDashboardDesc: 'Sélectionnez quel tableau de bord vous voulez exporter',
      export: 'Exporter',
      cancel: 'Annuler',
      success: 'Exporté!',
      successDesc: 'tuiles exportées avec succès',
      selectAll: 'Tout sélectionner',
      deselectAll: 'Tout désélectionner',
      selected: 'sélectionné',
      exporting: 'Exportation...',
      error: 'Erreur d\'exportation',
      errorDesc: 'Une erreur s\'est produite lors de l\'exportation',
      noTilesSelected: 'Aucune tuile sélectionnée',
      noTilesSelectedDesc: 'Sélectionnez au moins une tuile à exporter',
      filename: 'Nom du fichier',
      filenameDefault: 'mes-tuiles'
    },
    dashboard: {
      select: 'Sélectionner collection de tuiles',
      new: 'Nouvelle collection de tuiles',
      newTitle: 'Créer une nouvelle collection de tuiles',
      newDesc: 'Donnez un nom à votre nouvelle collection de tuiles',
      name: 'Nom de la collection de tuiles',
      namePlaceholder: 'Ma collection de tuiles',
      cancel: 'Annuler',
      create: 'Créer',
      creating: 'Création...',
      created: 'Collection de tuiles créée',
      createdDesc: 'Votre nouvelle collection de tuiles est prête',
      createError: 'Erreur lors de la création de la collection de tuiles',
      delete: 'Supprimer',
      deleted: 'Collection de tuiles supprimée',
      deletedDesc: 'La collection de tuiles a été supprimée',
      deleteError: 'Erreur lors de la suppression de la collection de tuiles',
      cannotDelete: 'Impossible de supprimer',
      cannotDeleteDesc: 'Vous devez avoir au moins une collection de tuiles',
      rename: 'Renommer',
      renameTitle: 'Renommer la collection de tuiles',
      renameDesc: 'Donnez un nouveau nom à votre collection de tuiles',
      renamed: 'Collection de tuiles renommée',
      renamedDesc: 'Le nom de votre collection de tuiles a été mis à jour',
      renameError: 'Erreur lors du renommage de la collection de tuiles',
    },
    
    // Donation page
    'donation.title': 'Soutenez Computerslet 3000',
    'donation.description': 'Computerslet 3000 vous rend-il heureux aussi ? Pensez à donner un pourboire à votre Pimp informatique. Ainsi, il peut s\'assurer que votre Computerslet 3000 continuera à faire son travail.',
    'donation.amount': 'Montant du don',
    'donation.custom': 'Montant personnalisé',
    'donation.donate': 'Faire un don',
    'donation.processing': 'Traitement en cours...',
    'donation.copied': 'Copié !',
    'donation.copySuccess': 'Numéro de compte copié dans le presse-papiers',
    'donation.copyError': 'Impossible de copier le numéro de compte',
    'donation.bankTransfer': 'Virement bancaire (gratuit)',
    'donation.bankDesc': 'Effectuer un virement vers notre compte KBC belge',
    'donation.accountNumber': 'Numéro de compte :',
    'donation.reference': 'Mentionner dans la communication : "Don Computerslet 3000"',
    'donation.onlinePayment': 'Paiement en ligne (Stripe)',
    'donation.onlineDesc': 'Payez en toute sécurité avec une carte de crédit, bancontact ou d\'autres méthodes de paiement',
    'donation.invalidAmount': 'Montant invalide',
    'donation.minAmount': 'Entrez un montant valide (minimum 1€)',
    'donation.stripeNotice': '* Les paiements en ligne sont traités par Stripe. Des frais de transaction peuvent s\'appliquer.',
    'donation.thankYou': 'Merci pour votre soutien ! ❤️',
    'donation.helpText': 'Votre contribution nous aide à améliorer Computerslet 3000.',
    'donation.processError': 'Une erreur s\'est produite lors du traitement du don',
    
    // Donation success
    'donationSuccess.title': 'Merci pour votre don !',
    'donationSuccess.description': 'Votre paiement a été traité avec succès. Nous apprécions énormément votre soutien !',
    'donationSuccess.helpText': 'Votre contribution nous aide à continuer de développer et d\'améliorer Computerslet 3000.',
    'donationSuccess.backButton': 'Retour à Computerslet 3000',
    'donationSuccess.autoRedirect': 'Vous serez automatiquement redirigé dans 10 secondes...',
    
    // Common
    'common.home': 'Accueil',
    'common.error': 'Une erreur s\'est produite',
    'common.success': 'Succès',
    
    // Export/Import
    'export.success': '📤 Export terminé',
    'export.successDesc': 'tuiles exportées.',
    'export.selectTiles': 'Sélectionner les tuiles à exporter',
    'export.selectTilesDesc': 'Choisissez les tuiles que vous voulez exporter.',
    'import.success': '📥 Import terminé',
    'import.successDesc': 'tuiles importées.',
    'import.error': 'Erreur d\'importation',
    'import.errorDesc': 'Le fichier n\'a pas pu être lu. Vérifiez le format.',
    
    // Logout
    'logout.success': 'Au revoir !',
    'logout.successDesc': 'Vous avez été déconnecté avec succès.',
    'logout.error': 'Erreur de déconnexion',
    
    // 404
    'notFound.title': '404',
    'notFound.description': 'Oops ! Page non trouvée',
    'notFound.backLink': 'Retour à l\'accueil',
  },
  es: {
    // Header
    'header.title': '🤖 Computerslet 3000',
    'header.support': 'Apóyanos',
    'header.export': 'Exportar',
    'header.import': 'Importar',
    'header.logout': 'Cerrar sesión',
    'header.language': 'Idioma',
    
    // Languages
    'language.nl': 'Holandés',
    'language.en': 'Inglés',
    'language.fr': 'Francés',
    'language.es': 'Español',
    'language.it': 'Italiano',
    'language.de': 'Alemán',
    
    // Auth
    'auth.title': 'Bienvenido a Computerslet 3000',
    'auth.subtitle': 'Crea y gestiona tus fichas de información',
    'auth.login': 'Iniciar sesión',
    'auth.signup': 'Registrarse',
    'auth.email': 'Correo electrónico',
    'auth.password': 'Contraseña',
    'auth.loginButton': 'Iniciar sesión',
    'auth.signupButton': 'Crear cuenta',
    'auth.loginSuccess': '¡Bienvenido de nuevo!',
    'auth.loginSuccessDesc': 'Has iniciado sesión correctamente.',
    'auth.signupSuccess': '¡Cuenta creada!',
    'auth.signupSuccessDesc': 'Revisa tu correo para confirmación.',
    'auth.loginError': 'Error de inicio de sesión',
    'auth.signupError': 'Error de registro',
    'auth.forgotPassword': '¿Olvidaste tu contraseña?',
    'auth.resetPassword': 'Restablecer contraseña',
    'auth.resetPasswordButton': 'Enviar instrucciones',
    'auth.resetPasswordSuccess': 'Instrucciones enviadas',
    'auth.resetPasswordSuccessDesc': 'Revisa tu email para las instrucciones',
    'auth.resetPasswordError': 'Error al restablecer contraseña',
    'auth.backToLogin': 'Volver al inicio de sesión',
    'auth.newPassword': 'Nueva contraseña',
    'auth.confirmPassword': 'Confirmar contraseña',
    'auth.updatePassword': 'Actualizar contraseña',
    'auth.updatePasswordButton': 'Actualizar contraseña',
    'auth.passwordsDoNotMatch': 'Las contraseñas no coinciden',
    'auth.passwordUpdated': 'Contraseña actualizada',
    'auth.passwordUpdatedDesc': 'Tu contraseña se ha actualizado correctamente',
    'auth.passwordUpdateError': 'Error al actualizar contraseña',
    
    // Auth errors
    'auth.error.invalidCredentials': 'Credenciales de inicio de sesión inválidas',
    'auth.error.userExists': 'Usuario ya registrado',
    'auth.error.emailNotConfirmed': 'Correo electrónico no confirmado',
    'auth.error.passwordTooShort': 'La contraseña debe tener al menos 6 caracteres',
    'auth.error.invalidEmail': 'Dirección de correo electrónico inválida',
    'auth.error.rateLimited': 'Demasiadas solicitudes. Inténtalo de nuevo más tarde',
    'auth.error.linkExpired': 'El enlace no es válido o ha expirado',
    'auth.error.samePassword': 'La nueva contraseña debe ser diferente de la anterior',
    
    // Dashboard
    'dashboard.loading': 'Cargando...',
    'dashboard.addTile': 'Agregar nueva ficha',
    'dashboard.editTile': 'Editar ficha',
    'dashboard.exampleTitle': 'Ejemplo',
    'dashboard.exampleContent': '¡Oye, acabas de copiar tu primera ficha! Puedes agregar más fichas con texto e imágenes personalizadas para facilitar la copia y pegado de tu trabajo/respuestas/mensajes repetitivos.',
    'dashboard.instruction': 'Haz clic en una ficha para copiar el texto. Usa ✏️ para editar o 🗑️ para eliminar.',
    
    // Tile form
    'tile.title': 'Título',
    'tile.content': 'Contenido',
    'tile.color': 'Color',
    'tile.save': 'Guardar',
    'tile.cancel': 'Cancelar',
    'tile.delete': 'Eliminar',
    'tile.created': 'Ficha creada',
    'tile.updated': 'Ficha actualizada',
    'tile.deleted': 'Ficha eliminada',
    'tile.subject': 'Asunto:',
    'tile.text': 'Texto:',
    'tile.editTitle': '✏️ Editar ficha',
    'tile.addTitle': '➕ Agregar nueva ficha',
    'tile.saveButton': '💾 Guardar',
    'tile.saving': 'Guardando...',
    'tile.copySms': 'Copiar versión SMS-segura',
    'tile.edit': 'Editar',
    'tile.deleteTooltip': 'Eliminar',
    'tile.confirmDelete': '¿Estás seguro de que quieres eliminar esta ficha?',
    'tile.copied': '✓ Texto copiado',
    'tile.copiedMultiFormat': 'Múltiples formatos: HTML, Markdown, RTF, texto plano',
    'tile.copiedHtmlPlain': 'HTML y texto plano copiados',
    'tile.copiedPlain': 'Texto plano copiado',
    'tile.smsModified': '⚠️ Advertencia: el texto fue modificado',
    'tile.smsCopied': '✓ Ficha copiada',
    'tile.copyFailed': 'Copia fallida',
    'tile.copyFailedDesc': 'No se pudo copiar la versión SMS al portapapeles',
    'tile.characters': 'caracteres',
    
    share: {
      button: 'Compartir',
      createLink: 'Enlace compartible',
      selectTiles: 'Seleccionar fichas para compartir',
      selectTilesDesc: 'Elige qué fichas quieres compartir con otros',
      selectDashboard: 'Elegir panel',
      selectDashboardDesc: 'Selecciona qué panel quieres compartir',
      collectionName: 'Nombre de la colección',
      collectionNamePlaceholder: 'Mis fichas compartidas',
      selectAll: 'Seleccionar todo',
      deselectAll: 'Deseleccionar todo',
      selected: 'seleccionado',
      cancel: 'Cancelar',
      creating: 'Creando...',
      success: 'Enlace compartible creado',
      successDesc: 'Ahora puedes compartir este enlace con otros',
      error: 'Error al crear enlace',
      linkCreated: '¡Enlace compartible creado!',
      linkCreatedDesc: 'Copia el enlace a continuación para compartir tus fichas',
      shareUrl: 'URL de compartir',
      copy: 'Copiar',
      copied: '¡Copiado!',
      copiedDesc: 'El enlace se ha copiado a tu portapapeles',
      copyError: 'Error al copiar',
      copyErrorDesc: 'No se pudo copiar el enlace',
      close: 'Cerrar',
      defaultName: 'Fichas compartidas',
      loading: 'Cargando...',
      notFound: 'Colección compartida no encontrada',
      notFoundDesc: 'Este enlace es inválido o ha expirado.',
      collectionDesc: 'Colección de fichas compartidas',
      noTiles: 'No hay fichas en esta colección',
    },

    export: {
      selectTiles: 'Seleccionar fichas para exportar',
      selectTilesDesc: 'Elige qué fichas quieres exportar',
      selectDashboard: 'Elegir panel',
      selectDashboardDesc: 'Selecciona qué panel quieres exportar',
      export: 'Exportar',
      cancel: 'Cancelar',
      success: '¡Exportado!',
      successDesc: 'fichas exportadas exitosamente',
      selectAll: 'Seleccionar todo',
      deselectAll: 'Deseleccionar todo',
      selected: 'seleccionado',
      exporting: 'Exportando...',
      error: 'Error de exportación',
      errorDesc: 'Ocurrió un error durante la exportación',
      noTilesSelected: 'No hay fichas seleccionadas',
      noTilesSelectedDesc: 'Selecciona al menos una ficha para exportar',
      filename: 'Nombre del archivo',
      filenameDefault: 'mis-fichas'
    },
    dashboard: {
      select: 'Seleccionar colección de fichas',
      new: 'Nueva colección de fichas',
      newTitle: 'Crear nueva colección de fichas',
      newDesc: 'Dale un nombre a tu nueva colección de fichas',
      name: 'Nombre de la colección de fichas',
      namePlaceholder: 'Mi colección de fichas',
      cancel: 'Cancelar',
      create: 'Crear',
      creating: 'Creando...',
      created: 'Colección de fichas creada',
      createdDesc: 'Tu nueva colección de fichas está lista',
      createError: 'Error al crear colección de fichas',
      delete: 'Eliminar',
      deleted: 'Colección de fichas eliminada',
      deletedDesc: 'La colección de fichas ha sido eliminada',
      deleteError: 'Error al eliminar colección de fichas',
      cannotDelete: 'No se puede eliminar',
      cannotDeleteDesc: 'Debes tener al menos una colección de fichas',
      rename: 'Renombrar',
      renameTitle: 'Renombrar colección de fichas',
      renameDesc: 'Dale un nuevo nombre a tu colección de fichas',
      renamed: 'Colección de fichas renombrada',
      renamedDesc: 'El nombre de tu colección de fichas ha sido actualizado',
      renameError: 'Error al renombrar colección de fichas',
    },
    
    // Donation page
    'donation.title': 'Apoya Computerslet 3000',
    'donation.description': '¿Computerslet 3000 también te hace feliz? Considera darle una propina a tu Proxeneta informático. Así puede asegurar que tu Computerslet 3000 siga haciendo su trabajo.',
    'donation.amount': 'Cantidad de donación',
    'donation.custom': 'Cantidad personalizada',
    'donation.donate': 'Donar',
    'donation.processing': 'Procesando...',
    'donation.copied': '¡Copiado!',
    'donation.copySuccess': 'Número de cuenta copiado al portapapeles',
    'donation.copyError': 'No se pudo copiar el número de cuenta',
    'donation.bankTransfer': 'Transferencia bancaria (gratis)',
    'donation.bankDesc': 'Transferir a nuestra cuenta KBC belga',
    'donation.accountNumber': 'Número de cuenta:',
    'donation.reference': 'Mencionar en comunicación: "Donación Computerslet 3000"',
    'donation.onlinePayment': 'Pago en línea (Stripe)',
    'donation.onlineDesc': 'Paga de forma segura con tarjeta de crédito, bancontact u otros métodos de pago',
    'donation.invalidAmount': 'Cantidad inválida',
    'donation.minAmount': 'Ingresa una cantidad válida (mínimo €1)',
    'donation.stripeNotice': '* Los pagos en línea son procesados por Stripe. Pueden aplicarse tarifas de transacción.',
    'donation.thankYou': '¡Gracias por tu apoyo! ❤️',
    'donation.helpText': 'Tu contribución nos ayuda a mejorar Computerslet 3000.',
    'donation.processError': 'Ocurrió un error al procesar la donación',
    
    // Donation success
    'donationSuccess.title': '¡Gracias por tu donación!',
    'donationSuccess.description': 'Tu pago se ha procesado correctamente. ¡Apreciamos enormemente tu apoyo!',
    'donationSuccess.helpText': 'Tu contribución nos ayuda a seguir desarrollando y mejorando Computerslet 3000.',
    'donationSuccess.backButton': 'Volver a Computerslet 3000',
    'donationSuccess.autoRedirect': 'Serás redirigido automáticamente en 10 segundos...',
    
    // Common
    'common.home': 'Inicio',
    'common.error': 'Ha ocurrido un error',
    'common.success': 'Éxito',
    
    // Export/Import
    'export.success': '📤 Exportación completada',
    'export.successDesc': 'fichas exportadas.',
    'export.selectTiles': 'Seleccionar fichas para exportar',
    'export.selectTilesDesc': 'Elige qué fichas quieres exportar.',
    'import.success': '📥 Importación completada',
    'import.successDesc': 'fichas importadas.',
    'import.error': 'Error de importación',
    'import.errorDesc': 'No se pudo leer el archivo. Verifica el formato.',
    
    // Logout
    'logout.success': '¡Adiós!',
    'logout.successDesc': 'Has cerrado sesión correctamente.',
    'logout.error': 'Error al cerrar sesión',
    
    // 404
    'notFound.title': '404',
    'notFound.description': '¡Oops! Página no encontrada',
    'notFound.backLink': 'Volver al inicio',
  },
  it: {
    // Header
    'header.title': '🤖 Computerslet 3000',
    'header.support': 'Sostienici',
    'header.export': 'Esporta',
    'header.import': 'Importa',
    'header.logout': 'Disconnetti',
    'header.language': 'Lingua',
    
    // Languages
    'language.nl': 'Olandese',
    'language.en': 'Inglese',
    'language.fr': 'Francese',
    'language.es': 'Spagnolo',
    'language.it': 'Italiano',
    'language.de': 'Tedesco',
    
    // Auth
    'auth.title': 'Benvenuto in Computerslet 3000',
    'auth.subtitle': 'Crea e gestisci le tue tessere informative',
    'auth.login': 'Accedi',
    'auth.signup': 'Registrati',
    'auth.email': 'Email',
    'auth.password': 'Password',
    'auth.loginButton': 'Accedi',
    'auth.signupButton': 'Crea account',
    'auth.loginSuccess': 'Bentornato!',
    'auth.loginSuccessDesc': 'Hai effettuato l\'accesso con successo.',
    'auth.signupSuccess': 'Account creato!',
    'auth.signupSuccessDesc': 'Controlla la tua email per la conferma.',
    'auth.loginError': 'Errore di accesso',
    'auth.signupError': 'Errore di registrazione',
    'auth.forgotPassword': 'Password dimenticata?',
    'auth.resetPassword': 'Reimposta password',
    'auth.resetPasswordButton': 'Invia istruzioni',
    'auth.resetPasswordSuccess': 'Istruzioni inviate',
    'auth.resetPasswordSuccessDesc': 'Controlla la tua email per le istruzioni',
    'auth.resetPasswordError': 'Errore nel reset password',
    'auth.backToLogin': 'Torna al login',
    'auth.newPassword': 'Nuova password',
    'auth.confirmPassword': 'Conferma password',
    'auth.updatePassword': 'Aggiorna password',
    'auth.updatePasswordButton': 'Aggiorna password',
    'auth.passwordsDoNotMatch': 'Le password non corrispondono',
    'auth.passwordUpdated': 'Password aggiornata',
    'auth.passwordUpdatedDesc': 'La tua password è stata aggiornata con successo',
    'auth.passwordUpdateError': 'Errore nell\'aggiornamento della password',
    
    // Auth errors
    'auth.error.invalidCredentials': 'Credenziali di accesso non valide',
    'auth.error.userExists': 'Utente già registrato',
    'auth.error.emailNotConfirmed': 'Email non confermata',
    'auth.error.passwordTooShort': 'La password deve essere di almeno 6 caratteri',
    'auth.error.invalidEmail': 'Indirizzo email non valido',
    'auth.error.rateLimited': 'Troppe richieste. Riprova più tardi',
    'auth.error.linkExpired': 'Il link non è valido o è scaduto',
    'auth.error.samePassword': 'La nuova password deve essere diversa dalla precedente',
    
    // Dashboard
    'dashboard.loading': 'Caricamento...',
    'dashboard.addTile': 'Aggiungi nuova tessera',
    'dashboard.editTile': 'Modifica tessera',
    'dashboard.exampleTitle': 'Esempio',
    'dashboard.exampleContent': 'Ehi, hai appena copiato la tua prima tessera! Puoi aggiungere più tessere con testo e immagini personalizzati per rendere molto più facile copiare-incollare il tuo lavoro/risposte/messaggi ripetitivi.',
    'dashboard.instruction': 'Clicca su una tessera per copiare il testo. Usa ✏️ per modificare o 🗑️ per eliminare.',
    
    // Tile form
    'tile.title': 'Titolo',
    'tile.content': 'Contenuto',
    'tile.color': 'Colore',
    'tile.save': 'Salva',
    'tile.cancel': 'Annulla',
    'tile.delete': 'Elimina',
    'tile.created': 'Tessera creata',
    'tile.updated': 'Tessera aggiornata',
    'tile.deleted': 'Tessera eliminata',
    'tile.subject': 'Argomento:',
    'tile.text': 'Testo:',
    'tile.editTitle': '✏️ Modifica tessera',
    'tile.addTitle': '➕ Aggiungi nuova tessera',
    'tile.saveButton': '💾 Salva',
    'tile.saving': 'Salvataggio...',
    'tile.copySms': 'Copia versione SMS-sicura',
    'tile.edit': 'Modifica',
    'tile.deleteTooltip': 'Elimina',
    'tile.confirmDelete': 'Sei sicuro di voler eliminare questa tessera?',
    'tile.copied': '✓ Testo copiato',
    'tile.copiedMultiFormat': 'Più formati: HTML, Markdown, RTF, testo semplice',
    'tile.copiedHtmlPlain': 'HTML e testo semplice copiati',
    'tile.copiedPlain': 'Testo semplice copiato',
    'tile.smsModified': '⚠️ Attenzione: il testo è stato modificato',
    'tile.smsCopied': '✓ Tessera copiata',
    'tile.copyFailed': 'Copia fallita',
    'tile.copyFailedDesc': 'Impossibile copiare la versione SMS negli appunti',
    'tile.characters': 'caratteri',
    
    share: {
      button: 'Condividi',
      createLink: 'Link condivisibile',
      selectTiles: 'Seleziona tessere da condividere',
      selectTilesDesc: 'Scegli quali tessere vuoi condividere con altri',
      selectDashboard: 'Scegli dashboard',
      selectDashboardDesc: 'Seleziona quale dashboard vuoi condividere',
      collectionName: 'Nome della collezione',
      collectionNamePlaceholder: 'Le mie tessere condivise',
      selectAll: 'Seleziona tutto',
      deselectAll: 'Deseleziona tutto',
      selected: 'selezionato',
      cancel: 'Annulla',
      creating: 'Creazione...',
      success: 'Link condivisibile creato',
      successDesc: 'Ora puoi condividere questo link con altri',
      error: 'Errore nella creazione del link',
      linkCreated: 'Link condivisibile creato!',
      linkCreatedDesc: 'Copia il link qui sotto per condividere le tue tessere',
      shareUrl: 'URL di condivisione',
      copy: 'Copia',
      copied: 'Copiato!',
      copiedDesc: 'Il link è stato copiato negli appunti',
      copyError: 'Errore di copia',
      copyErrorDesc: 'Impossibile copiare il link',
      close: 'Chiudi',
      defaultName: 'Tessere condivise',
      loading: 'Caricamento...',
      notFound: 'Collezione condivisa non trovata',
      notFoundDesc: 'Questo link non è valido o è scaduto.',
      collectionDesc: 'Collezione di tessere condivise',
      noTiles: 'Nessuna tessera in questa collezione',
    },

    export: {
      selectTiles: 'Seleziona tessere da esportare',
      selectTilesDesc: 'Scegli quali tessere vuoi esportare',
      selectDashboard: 'Scegli dashboard',
      selectDashboardDesc: 'Seleziona quale dashboard vuoi esportare',
      export: 'Esporta',
      cancel: 'Annulla',
      success: 'Esportato!',
      successDesc: 'tessere esportate con successo',
      selectAll: 'Seleziona tutto',
      deselectAll: 'Deseleziona tutto',
      selected: 'selezionato',
      exporting: 'Esportazione...',
      error: 'Errore di esportazione',
      errorDesc: 'Si è verificato un errore durante l\'esportazione',
      noTilesSelected: 'Nessuna tessera selezionata',
      noTilesSelectedDesc: 'Seleziona almeno una tessera da esportare',
      filename: 'Nome del file',
      filenameDefault: 'le-mie-tessere'
    },
    dashboard: {
      select: 'Seleziona collezione di tessere',
      new: 'Nuova collezione di tessere',
      newTitle: 'Crea nuova collezione di tessere',
      newDesc: 'Dai un nome alla tua nuova collezione di tessere',
      name: 'Nome della collezione di tessere',
      namePlaceholder: 'La mia collezione di tessere',
      cancel: 'Annulla',
      create: 'Crea',
      creating: 'Creazione...',
      created: 'Collezione di tessere creata',
      createdDesc: 'La tua nuova collezione di tessere è pronta',
      createError: 'Errore nella creazione della collezione di tessere',
      delete: 'Elimina',
      deleted: 'Collezione di tessere eliminata',
      deletedDesc: 'La collezione di tessere è stata eliminata',
      deleteError: 'Errore nell\'eliminazione della collezione di tessere',
      cannotDelete: 'Impossibile eliminare',
      cannotDeleteDesc: 'Devi avere almeno una collezione di tessere',
      rename: 'Rinomina',
      renameTitle: 'Rinomina collezione di tessere',
      renameDesc: 'Dai un nuovo nome alla tua collezione di tessere',
      renamed: 'Collezione di tessere rinominata',
      renamedDesc: 'Il nome della tua collezione di tessere è stato aggiornato',
      renameError: 'Errore nel rinominare la collezione di tessere',
    },
    
    // Donation page
    'donation.title': 'Sostieni Computerslet 3000',
    'donation.description': 'Computerslet 3000 ti rende felice anche tu? Considera di dare una mancia al tuo Magnaccia informatico. Così può assicurarsi che il tuo Computerslet 3000 continui a fare il suo lavoro.',
    'donation.amount': 'Importo donazione',
    'donation.custom': 'Importo personalizzato',
    'donation.donate': 'Dona',
    'donation.processing': 'Elaborazione...',
    'donation.copied': 'Copiato!',
    'donation.copySuccess': 'Numero di conto copiato negli appunti',
    'donation.copyError': 'Impossibile copiare il numero di conto',
    'donation.bankTransfer': 'Bonifico bancario (gratuito)',
    'donation.bankDesc': 'Trasferisci al nostro conto KBC belga',
    'donation.accountNumber': 'Numero di conto:',
    'donation.reference': 'Menzionare nella comunicazione: "Donazione Computerslet 3000"',
    'donation.onlinePayment': 'Pagamento online (Stripe)',
    'donation.onlineDesc': 'Paga in sicurezza con carta di credito, bancontact o altri metodi di pagamento',
    'donation.invalidAmount': 'Importo non valido',
    'donation.minAmount': 'Inserisci un importo valido (minimo €1)',
    'donation.stripeNotice': '* I pagamenti online sono elaborati da Stripe. Potrebbero applicarsi commissioni di transazione.',
    'donation.thankYou': 'Grazie per il tuo supporto! ❤️',
    'donation.helpText': 'Il tuo contributo ci aiuta a migliorare Computerslet 3000.',
    'donation.processError': 'Si è verificato un errore durante l\'elaborazione della donazione',
    
    // Donation success
    'donationSuccess.title': 'Grazie per la tua donazione!',
    'donationSuccess.description': 'Il tuo pagamento è stato elaborato con successo. Apprezziamo enormemente il tuo supporto!',
    'donationSuccess.helpText': 'Il tuo contributo ci aiuta a continuare a sviluppare e migliorare Computerslet 3000.',
    'donationSuccess.backButton': 'Torna a Computerslet 3000',
    'donationSuccess.autoRedirect': 'Sarai reindirizzato automaticamente tra 10 secondi...',
    
    // Common
    'common.home': 'Home',
    'common.error': 'Si è verificato un errore',
    'common.success': 'Successo',
    
    // Export/Import
    'export.success': '📤 Esportazione completata',
    'export.successDesc': 'tessere esportate.',
    'export.selectTiles': 'Seleziona tessere da esportare',
    'export.selectTilesDesc': 'Scegli quali tessere vuoi esportare.',
    'import.success': '📥 Importazione completata',
    'import.successDesc': 'tessere importate.',
    'import.error': 'Errore di importazione',
    'import.errorDesc': 'Non è stato possibile leggere il file. Controlla il formato.',
    
    // Logout
    'logout.success': 'Arrivederci!',
    'logout.successDesc': 'Ti sei disconnesso con successo.',
    'logout.error': 'Errore di disconnessione',
    
    // 404
    'notFound.title': '404',
    'notFound.description': 'Oops! Pagina non trovata',
    'notFound.backLink': 'Torna alla home',
  },
  de: {
    // Header
    'header.title': '🤖 Computerslet 3000',
    'header.support': 'Unterstütze uns',
    'header.export': 'Exportieren',
    'header.import': 'Importieren',
    'header.logout': 'Abmelden',
    'header.language': 'Sprache',
    
    // Languages
    'language.nl': 'Niederländisch',
    'language.en': 'Englisch',
    'language.fr': 'Französisch',
    'language.es': 'Spanisch',
    'language.it': 'Italienisch',
    'language.de': 'Deutsch',
    
    // Auth
    'auth.title': 'Willkommen bei Computerslet 3000',
    'auth.subtitle': 'Erstelle und verwalte deine Informationskacheln',
    'auth.login': 'Anmelden',
    'auth.signup': 'Registrieren',
    'auth.email': 'E-Mail',
    'auth.password': 'Passwort',
    'auth.loginButton': 'Anmelden',
    'auth.signupButton': 'Konto erstellen',
    'auth.loginSuccess': 'Willkommen zurück!',
    'auth.loginSuccessDesc': 'Du hast dich erfolgreich angemeldet.',
    'auth.signupSuccess': 'Konto erstellt!',
    'auth.signupSuccessDesc': 'Überprüfe deine E-Mail zur Bestätigung.',
    'auth.loginError': 'Anmeldefehler',
    'auth.signupError': 'Registrierungsfehler',
    'auth.forgotPassword': 'Passwort vergessen?',
    'auth.resetPassword': 'Passwort zurücksetzen',
    'auth.resetPasswordButton': 'Anweisungen senden',
    'auth.resetPasswordSuccess': 'Anweisungen gesendet',
    'auth.resetPasswordSuccessDesc': 'Überprüfen Sie Ihre E-Mail für Anweisungen',
    'auth.resetPasswordError': 'Fehler beim Zurücksetzen',
    'auth.backToLogin': 'Zurück zur Anmeldung',
    'auth.newPassword': 'Neues Passwort',
    'auth.confirmPassword': 'Passwort bestätigen',
    'auth.updatePassword': 'Passwort aktualisieren',
    'auth.updatePasswordButton': 'Passwort aktualisieren',
    'auth.passwordsDoNotMatch': 'Passwörter stimmen nicht überein',
    'auth.passwordUpdated': 'Passwort aktualisiert',
    'auth.passwordUpdatedDesc': 'Ihr Passwort wurde erfolgreich aktualisiert',
    'auth.passwordUpdateError': 'Fehler beim Aktualisieren des Passworts',
    
    // Auth errors
    'auth.error.invalidCredentials': 'Ungültige Anmeldedaten',
    'auth.error.userExists': 'Benutzer bereits registriert',
    'auth.error.emailNotConfirmed': 'E-Mail nicht bestätigt',
    'auth.error.passwordTooShort': 'Passwort muss mindestens 6 Zeichen lang sein',
    'auth.error.invalidEmail': 'Ungültige E-Mail-Adresse',
    'auth.error.rateLimited': 'Zu viele Anfragen. Bitte versuchen Sie es später erneut',
    'auth.error.linkExpired': 'Link ist ungültig oder abgelaufen',
    'auth.error.samePassword': 'Neues Passwort muss sich vom alten unterscheiden',
    
    // Dashboard
    'dashboard.loading': 'Lädt...',
    'dashboard.addTile': 'Neue Kachel hinzufügen',
    'dashboard.editTile': 'Kachel bearbeiten',
    'dashboard.exampleTitle': 'Beispiel',
    'dashboard.exampleContent': 'Hey, du hast gerade deine erste Kachel kopiert! Du kannst weitere Kacheln mit benutzerdefiniertem Text und Bildern hinzufügen, um das Kopieren und Einfügen deiner sich wiederholenden Arbeiten/Antworten/Nachrichten viel einfacher zu machen.',
    'dashboard.instruction': 'Klicke auf eine Kachel, um den Text zu kopieren. Verwende ✏️ zum Bearbeiten oder 🗑️ zum Löschen.',
    
    // Tile form
    'tile.title': 'Titel',
    'tile.content': 'Inhalt',
    'tile.color': 'Farbe',
    'tile.save': 'Speichern',
    'tile.cancel': 'Abbrechen',
    'tile.delete': 'Löschen',
    'tile.created': 'Kachel erstellt',
    'tile.updated': 'Kachel aktualisiert',
    'tile.deleted': 'Kachel gelöscht',
    'tile.subject': 'Betreff:',
    'tile.text': 'Text:',
    'tile.editTitle': '✏️ Kachel bearbeiten',
    'tile.addTitle': '➕ Neue Kachel hinzufügen',
    'tile.saveButton': '💾 Speichern',
    'tile.saving': 'Speichern...',
    'tile.copySms': 'SMS-sichere Version kopieren',
    'tile.edit': 'Bearbeiten',
    'tile.deleteTooltip': 'Löschen',
    'tile.confirmDelete': 'Bist du sicher, dass du diese Kachel löschen möchtest?',
    'tile.copied': '✓ Text kopiert',
    'tile.copiedMultiFormat': 'Mehrere Formate: HTML, Markdown, RTF, Klartext',
    'tile.copiedHtmlPlain': 'HTML und Klartext kopiert',
    'tile.copiedPlain': 'Klartext kopiert',
    'tile.smsModified': '⚠️ Warnung: Text wurde geändert',
    'tile.smsCopied': '✓ Kachel kopiert',
    'tile.copyFailed': 'Kopieren fehlgeschlagen',
    'tile.copyFailedDesc': 'SMS-Version konnte nicht in Zwischenablage kopiert werden',
    'tile.characters': 'Zeichen',
    
    share: {
      button: 'Teilen',
      createLink: 'Teilbarer Link',
      selectTiles: 'Kacheln zum Teilen auswählen',
      selectTilesDesc: 'Wähle, welche Kacheln du mit anderen teilen möchtest',
      selectDashboard: 'Dashboard wählen',
      selectDashboardDesc: 'Wähle, welches Dashboard du teilen möchtest',
      collectionName: 'Sammlungsname',
      collectionNamePlaceholder: 'Meine geteilten Kacheln',
      selectAll: 'Alle auswählen',
      deselectAll: 'Alle abwählen',
      selected: 'ausgewählt',
      cancel: 'Abbrechen',
      creating: 'Erstellen...',
      success: 'Teilbarer Link erstellt',
      successDesc: 'Du kannst diesen Link jetzt mit anderen teilen',
      error: 'Fehler beim Erstellen des Links',
      linkCreated: 'Teilbarer Link erstellt!',
      linkCreatedDesc: 'Kopiere den Link unten, um deine Kacheln zu teilen',
      shareUrl: 'Teilen-URL',
      copy: 'Kopieren',
      copied: 'Kopiert!',
      copiedDesc: 'Der Link wurde in die Zwischenablage kopiert',
      copyError: 'Kopieren fehlgeschlagen',
      copyErrorDesc: 'Der Link konnte nicht kopiert werden',
      close: 'Schließen',
      defaultName: 'Geteilte Kacheln',
      loading: 'Lädt...',
      notFound: 'Geteilte Sammlung nicht gefunden',
      notFoundDesc: 'Dieser Link ist ungültig oder abgelaufen.',
      collectionDesc: 'Geteilte Kachelsammlung',
      noTiles: 'Keine Kacheln in dieser Sammlung',
    },

    export: {
      selectTiles: 'Kacheln zum Exportieren auswählen',
      selectTilesDesc: 'Wähle, welche Kacheln du exportieren möchtest',
      selectDashboard: 'Dashboard wählen',
      selectDashboardDesc: 'Wähle, welches Dashboard du exportieren möchtest',
      export: 'Exportieren',
      cancel: 'Abbrechen',
      success: 'Exportiert!',
      successDesc: 'Kacheln erfolgreich exportiert',
      selectAll: 'Alle auswählen',
      deselectAll: 'Alle abwählen',
      selected: 'ausgewählt',
      exporting: 'Exportiere...',
      error: 'Export-Fehler',
      errorDesc: 'Bei dem Export ist ein Fehler aufgetreten',
      noTilesSelected: 'Keine Kacheln ausgewählt',
      noTilesSelectedDesc: 'Wähle mindestens eine Kachel zum Exportieren aus',
      filename: 'Dateiname',
      filenameDefault: 'meine-kacheln'
    },
    dashboard: {
      select: 'Kachelsammlung auswählen',
      new: 'Neue Kachelsammlung',
      newTitle: 'Neue Kachelsammlung erstellen',
      newDesc: 'Gib deiner neuen Kachelsammlung einen Namen',
      name: 'Kachelsammlung-Name',
      namePlaceholder: 'Meine Kachelsammlung',
      cancel: 'Abbrechen',
      create: 'Erstellen',
      creating: 'Erstellen...',
      created: 'Kachelsammlung erstellt',
      createdDesc: 'Deine neue Kachelsammlung ist bereit',
      createError: 'Fehler beim Erstellen der Kachelsammlung',
      delete: 'Löschen',
      deleted: 'Kachelsammlung gelöscht',
      deletedDesc: 'Die Kachelsammlung wurde gelöscht',
      deleteError: 'Fehler beim Löschen der Kachelsammlung',
      cannotDelete: 'Kann nicht löschen',
      cannotDeleteDesc: 'Du musst mindestens eine Kachelsammlung haben',
      rename: 'Umbenennen',
      renameTitle: 'Kachelsammlung umbenennen',
      renameDesc: 'Gib deiner Kachelsammlung einen neuen Namen',
      renamed: 'Kachelsammlung umbenannt',
      renamedDesc: 'Dein Kachelsammlung-Name wurde aktualisiert',
      renameError: 'Fehler beim Umbenennen der Kachelsammlung',
    },
    
    // Donation page
    'donation.title': 'Unterstütze Computerslet 3000',
    'donation.description': 'Macht dich Computerslet 3000 auch so glücklich? Erwäge, deinem Computer-Zuhälter ein Trinkgeld zu geben. So kann er dafür sorgen, dass dein Computerslet 3000 weiterhin ihre Arbeit macht.',
    'donation.amount': 'Spendenbetrag',
    'donation.custom': 'Benutzerdefinierter Betrag',
    'donation.donate': 'Spenden',
    'donation.processing': 'Verarbeitung...',
    'donation.copied': 'Kopiert!',
    'donation.copySuccess': 'Kontonummer in die Zwischenablage kopiert',
    'donation.copyError': 'Kontonummer konnte nicht kopiert werden',
    'donation.bankTransfer': 'Banküberweisung (kostenlos)',
    'donation.bankDesc': 'Überweisung auf unser belgisches KBC-Konto',
    'donation.accountNumber': 'Kontonummer:',
    'donation.reference': 'Im Verwendungszweck erwähnen: "Spende Computerslet 3000"',
    'donation.onlinePayment': 'Online-Zahlung (Stripe)',
    'donation.onlineDesc': 'Sicher zahlen mit Kreditkarte, Bancontact oder anderen Zahlungsmethoden',
    'donation.invalidAmount': 'Ungültiger Betrag',
    'donation.minAmount': 'Geben Sie einen gültigen Betrag ein (mindestens €1)',
    'donation.stripeNotice': '* Online-Zahlungen werden von Stripe verarbeitet. Es können Transaktionsgebühren anfallen.',
    'donation.thankYou': 'Danke für deine Unterstützung! ❤️',
    'donation.helpText': 'Dein Beitrag hilft uns, Computerslet 3000 zu verbessern.',
    'donation.processError': 'Ein Fehler ist bei der Verarbeitung der Spende aufgetreten',
    
    // Donation success
    'donationSuccess.title': 'Danke für deine Spende!',
    'donationSuccess.description': 'Deine Zahlung wurde erfolgreich verarbeitet. Wir schätzen deine Unterstützung sehr!',
    'donationSuccess.helpText': 'Dein Beitrag hilft uns, Computerslet 3000 weiter zu entwickeln und zu verbessern.',
    'donationSuccess.backButton': 'Zurück zu Computerslet 3000',
    'donationSuccess.autoRedirect': 'Du wirst automatisch in 10 Sekunden weitergeleitet...',
    
    // Common
    'common.home': 'Startseite',
    'common.error': 'Ein Fehler ist aufgetreten',
    'common.success': 'Erfolgreich',
    
    // Export/Import
    'export.success': '📤 Export abgeschlossen',
    'export.successDesc': 'Kacheln exportiert.',
    'export.selectTiles': 'Kacheln zum Exportieren auswählen',
    'export.selectTilesDesc': 'Wähle die Kacheln aus, die du exportieren möchtest.',
    'import.success': '📥 Import abgeschlossen',
    'import.successDesc': 'Kacheln importiert.',
    'import.error': 'Import-Fehler',
    'import.errorDesc': 'Die Datei konnte nicht gelesen werden. Überprüfe das Format.',
    
    // Logout
    'logout.success': 'Auf Wiedersehen!',
    'logout.successDesc': 'Du hast dich erfolgreich abgemeldet.',
    'logout.error': 'Abmeldefehler',
    
    // 404
    'notFound.title': '404',
    'notFound.description': 'Oops! Seite nicht gefunden',
    'notFound.backLink': 'Zurück zur Startseite',
  },
};

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>(() => {
    const saved = localStorage.getItem('language');
    return (saved as Language) || 'nl';
  });

  useEffect(() => {
    localStorage.setItem('language', language);
  }, [language]);

  const t = (key: string): string => {
    // Handle only specific nested keys that we actually have as objects
    const nestedKeys = [
      'share.button', 'share.createLink', 'share.selectTiles', 'share.selectTilesDesc', 
      'share.selectDashboard', 'share.selectDashboardDesc',
      'share.collectionName', 'share.collectionNamePlaceholder', 'share.selectAll', 
      'share.deselectAll', 'share.selected', 'share.cancel', 'share.creating',
      'share.success', 'share.successDesc', 'share.error', 'share.linkCreated',
      'share.linkCreatedDesc', 'share.shareUrl', 'share.copy', 'share.copied',
      'share.copiedDesc', 'share.copyError', 'share.copyErrorDesc', 'share.close',
      'share.defaultName', 'share.loading', 'share.notFound', 'share.notFoundDesc',
      'share.collectionDesc', 'share.noTiles', 'export.selectDashboard', 'export.selectDashboardDesc',
      'dashboard.new', 'dashboard.delete', 'dashboard.rename'
    ];
    
    if (nestedKeys.includes(key)) {
      const keys = key.split('.');
      let value: any = translations[language];
      
      for (const k of keys) {
        if (value && typeof value === 'object' && k in value) {
          value = value[k];
        } else {
          return key; // fallback to key if not found
        }
      }
      
      return typeof value === 'string' ? value : key;
    }
    
    // For all other keys, return direct lookup
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};