// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://qxlcoqiholwpjfzzxaqy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF4bGNvcWlob2x3cGpmenp4YXF5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ1NDMwNTQsImV4cCI6MjA3MDExOTA1NH0.2oC-XrPDo2cCWNRIUNTXYFQrv0gglaiKX0vbpPBR-aQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});